include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'build-image.template.yaml'
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'helm.template.yaml'

default:
  tags:
    - adcorn-dev

variables:
  APP_NAME: "website"
  APP_NAMESPACE: "${CI_PROJECT_ROOT_NAMESPACE}-${CI_PROJECT_NAME}"
  ENVIRONMENT: dev
  KUBECONFIG_B64: $DEV_KUBECONFIG_B64

stages:
  - build
  - deploy

build:app:
  stage: build
  extends: .build_image
  variables:
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_CPU_LIMIT: 4
    KUBERNETES_MEMORY_REQUEST: 4096Mi
    KUBERNETES_MEMORY_LIMIT: 4096Mi
    APP_NAME: "app"
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=development --build-arg REACT_APP_API_URL=https://backend-dev.defihelper.info/api --build-arg REACT_APP_LAUNCH_APP_URL=https://app-dev.defihelper.info/ --build-arg REACT_APP_AMCHARTS_LICENCE=${REACT_APP_AMCHARTS_LICENCE} --build-arg REACT_APP_UNISENDER_API=${REACT_APP_UNISENDER_API} --build-arg REACT_APP_DEMO_LINK=https://app-dev.defihelper.info/demo"
    - if: $CI_COMMIT_REF_NAME == "release"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=production --build-arg REACT_APP_API_URL=https://backend.defihelper.io/api --build-arg REACT_APP_LAUNCH_APP_URL=https://app.defihelper.io/ --build-arg REACT_APP_AMCHARTS_LICENCE=${REACT_APP_AMCHARTS_LICENCE} --build-arg REACT_APP_UNISENDER_API=${REACT_APP_UNISENDER_API} --build-arg REACT_APP_DEMO_LINK=https://app.defihelper.io/demo"
        ENVIRONMENT: prod
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

deploy:
  extends: .helm_upgrade
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "release"'
      when: on_success
      variables:
        KUBECONFIG_B64: $PROD_KUBECONFIG_B64
        ENVIRONMENT: prod
    - if: '$CI_COMMIT_REF_NAME == "master"'
