/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type CollectFee = ContractEventLog<{
  handler: string;
  amount: string;
  0: string;
  1: string;
}>;
export type Payback = ContractEventLog<{
  from: string;
  token: string;
  amount: string;
  0: string;
  1: string;
  2: string;
}>;
export type Withdraw = ContractEventLog<{
  transitId: string;
  to: string;
  token: string;
  amount: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;

export interface BurgerTransit extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BurgerTransit;
  clone(): BurgerTransit;
  methods: {
    changeDevelopFee(
      _amount: number | string
    ): NonPayableTransactionObject<void>;

    changeDevelopWallet(_wallet: string): NonPayableTransactionObject<void>;

    changeSigner(_wallet: string): NonPayableTransactionObject<void>;

    collectFee(): NonPayableTransactionObject<void>;

    developFee(): NonPayableTransactionObject<string>;

    developWallet(): NonPayableTransactionObject<string>;

    executedMap(arg0: string | number[]): NonPayableTransactionObject<boolean>;

    owner(): NonPayableTransactionObject<string>;

    pairFor(arg0: string): NonPayableTransactionObject<string>;

    pairTo(arg0: string): NonPayableTransactionObject<string>;

    paybackTransit(
      _token: string,
      _amount: number | string
    ): PayableTransactionObject<void>;

    signWallet(): NonPayableTransactionObject<string>;

    totalFee(): NonPayableTransactionObject<string>;

    withdrawTransitToken(
      _signature: string | number[],
      _transitId: string | number[],
      _amount: number | string,
      _token: string,
      _name: string,
      _symbol: string,
      _decimals: number | string
    ): PayableTransactionObject<void>;
  };
  events: {
    CollectFee(cb?: Callback<CollectFee>): EventEmitter;
    CollectFee(options?: EventOptions, cb?: Callback<CollectFee>): EventEmitter;

    Payback(cb?: Callback<Payback>): EventEmitter;
    Payback(options?: EventOptions, cb?: Callback<Payback>): EventEmitter;

    Withdraw(cb?: Callback<Withdraw>): EventEmitter;
    Withdraw(options?: EventOptions, cb?: Callback<Withdraw>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "CollectFee", cb: Callback<CollectFee>): void;
  once(
    event: "CollectFee",
    options: EventOptions,
    cb: Callback<CollectFee>
  ): void;

  once(event: "Payback", cb: Callback<Payback>): void;
  once(event: "Payback", options: EventOptions, cb: Callback<Payback>): void;

  once(event: "Withdraw", cb: Callback<Withdraw>): void;
  once(event: "Withdraw", options: EventOptions, cb: Callback<Withdraw>): void;
}
