name: Mirror and run GitLab CI

on: [push]

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://adcorn-prod.gitlab.yandexcloud.net/defihelper/website"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "adcorn-prod.gitlab.yandexcloud.net"
        GITLAB_USERNAME: "vkomissarov"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_ADCORN_PROD_PASSWORD }}
        GITLAB_PROJECT_ID: "3"
        GITHUB_TOKEN: ${{ secrets.GTHUB_TOKEN }}
